services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - ENVIRONMENT=development
      - WATCHFILES_FORCE_POLLING=true
      - MOCK_EXTERNAL_APIs=true          # <-- Turn the mock OFF so we hit the real APIs
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
